export const USER_REQUEST = "USER_REQUEST";
export const USER_FAIL = "USER_FAIL";
export const USER_SUCCESS = "USER_SUCCESS";

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGOUT_SUCCESS= "LOGOUT_SUCCESS";
export const LOGOUT_FAIL= "LOGOUT_FAIL";

export const CLEAR_ERROR = "CLEAR_ERROR";